#!/bin/bash
################################################################################
# install.sh
# 
# Purpose: INSTALL phase - import root filesystems + finalize boot artifacts + cleanup
#          Deploys OS images to partitions and configures boot loader
#
# Usage: sudo ./install.sh
################################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$PROJECT_ROOT/artifacts/logs"
LOG_FILE="$LOG_DIR/install_$(date +%Y%m%d_%H%M%S).log"
ARTIFACTS_DIR="$PROJECT_ROOT/artifacts"
FIRMWARE_DIR="$ARTIFACTS_DIR/firmware"
IMAGES_DIR="$ARTIFACTS_DIR/images"
PARTITION_MAP="$LOG_DIR/partition_map.txt"

# Ensure log directory exists
mkdir -p "$LOG_DIR"

# Logging functions
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*" | tee -a "$LOG_FILE"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

log "==================================================================="
log "Starting INSTALL phase"
log "==================================================================="

# Check if partition map exists
if [[ ! -f "$PARTITION_MAP" ]]; then
    log_error "Partition map not found: $PARTITION_MAP"
    log_error "Please run prepare.sh first"
    exit 1
fi

# Source partition map
log "Loading partition map..."
source "$PARTITION_MAP"

# Verify mount points
if [[ ! -d "$MOUNT_FIRMWARE" ]] || [[ ! -d "$MOUNT_BOOT" ]]; then
    log_error "Mount points not found. Please run prepare.sh first."
    exit 1
fi

log "Loaded partition configuration:"
log "  Firmware: $FIRMWARE_PARTITION -> $MOUNT_FIRMWARE"
log "  Boot:     $BOOT_PARTITION -> $MOUNT_BOOT"
log "  Kubuntu:  $KUBUNTU_PARTITION -> $MOUNT_KUBUNTU"
log "  Fedora:   $FEDORA_PARTITION -> $MOUNT_FEDORA"
log "  Data:     $DATA_PARTITION -> $MOUNT_DATA"

log "Phase 1: Installing Firmware Files"
log "-------------------------------------------------------------------"

if [[ ! -d "$FIRMWARE_DIR" ]]; then
    log_error "Firmware directory not found: $FIRMWARE_DIR"
    log_error "Please run acquire.sh first"
    exit 1
fi

log_info "Copying firmware files to $MOUNT_FIRMWARE..."
cp -v "$FIRMWARE_DIR"/*.elf "$MOUNT_FIRMWARE/" 2>&1 | tee -a "$LOG_FILE" || log_warning "Some .elf files may not exist"
cp -v "$FIRMWARE_DIR"/*.dat "$MOUNT_FIRMWARE/" 2>&1 | tee -a "$LOG_FILE" || log_warning "Some .dat files may not exist"
cp -v "$FIRMWARE_DIR"/*.bin "$MOUNT_FIRMWARE/" 2>&1 | tee -a "$LOG_FILE" || log_warning "Some .bin files may not exist"
cp -v "$FIRMWARE_DIR"/*.dtb "$MOUNT_FIRMWARE/" 2>&1 | tee -a "$LOG_FILE" || log_warning "Some .dtb files may not exist"

if [[ -f "$FIRMWARE_DIR/config.txt" ]]; then
    cp -v "$FIRMWARE_DIR/config.txt" "$MOUNT_FIRMWARE/" 2>&1 | tee -a "$LOG_FILE"
    log_success "  Copied config.txt"
else
    log_warning "  config.txt not found in firmware directory"
fi

sync

log "Phase 2: Setting up Boot Partition"
log "-------------------------------------------------------------------"

log_info "Creating directory structure on boot partition..."
mkdir -p "$MOUNT_BOOT"/{EFI/BOOT,grub,kernels/{kubuntu,fedora}}

# Create a basic GRUB configuration
log_info "Generating GRUB configuration..."

# Get UUIDs for partitions
KUBUNTU_UUID=$(blkid -s UUID -o value "$KUBUNTU_PARTITION")
FEDORA_UUID=$(blkid -s UUID -o value "$FEDORA_PARTITION")

log_info "  Kubuntu UUID: $KUBUNTU_UUID"
log_info "  Fedora UUID:  $FEDORA_UUID"

GRUB_CFG="$MOUNT_BOOT/grub/grub.cfg"
cat > "$GRUB_CFG" <<EOF
# GRUB Configuration for Raspberry Pi 5 Multiboot
# Generated by install.sh on $(date)

set timeout=10
set default=0

# Load video drivers
insmod all_video
insmod gfxterm

# Set graphics mode
set gfxmode=auto
terminal_output gfxterm

# Theme
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

# Kubuntu Entry
menuentry "Kubuntu" {
    search --no-floppy --fs-uuid --set=root $KUBUNTU_UUID
    linux /boot/vmlinuz root=UUID=$KUBUNTU_UUID ro quiet splash
    initrd /boot/initrd.img
}

# Fedora Entry
menuentry "Fedora" {
    search --no-floppy --fs-uuid --set=root $FEDORA_UUID
    linux /boot/vmlinuz root=UUID=$FEDORA_UUID ro quiet
    initrd /boot/initrd.img
}

# Recovery options
menuentry "Kubuntu (Recovery Mode)" {
    search --no-floppy --fs-uuid --set=root $KUBUNTU_UUID
    linux /boot/vmlinuz root=UUID=$KUBUNTU_UUID ro recovery nomodeset
    initrd /boot/initrd.img
}

menuentry "Fedora (Recovery Mode)" {
    search --no-floppy --fs-uuid --set=root $FEDORA_UUID
    linux /boot/vmlinuz root=UUID=$FEDORA_UUID ro recovery nomodeset
    initrd /boot/initrd.img
}

# System options
menuentry "Reboot" {
    reboot
}

menuentry "Power Off" {
    halt
}
EOF

log_success "  Generated GRUB configuration: $GRUB_CFG"

# Create grubenv file
touch "$MOUNT_BOOT/grub/grubenv"

log "Phase 3: Installing OS Images"
log "-------------------------------------------------------------------"

# Function to extract and install an OS image
install_os_image() {
    local image_file="$1"
    local target_mount="$2"
    local os_name="$3"
    
    if [[ ! -f "$image_file" ]]; then
        log_warning "Image file not found: $image_file"
        log_warning "Skipping $os_name installation"
        return 1
    fi
    
    log_info "Installing $os_name from $image_file..."
    log_info "  Target: $target_mount"
    
    # Create temporary mount point for loop device
    local loop_mount="/tmp/loop_$os_name"
    mkdir -p "$loop_mount"
    
    # Decompress if needed
    local work_image="$image_file"
    if [[ "$image_file" == *.xz ]]; then
        log_info "  Decompressing XZ archive..."
        local decompressed="/tmp/${os_name}_temp.img"
        xz -dc "$image_file" > "$decompressed"
        work_image="$decompressed"
    fi
    
    # Mount the image
    log_info "  Mounting image via loop device..."
    local loop_device=$(losetup -f)
    losetup -P "$loop_device" "$work_image"
    
    # Find the root partition in the image (usually partition 2)
    local root_part="${loop_device}p2"
    if [[ ! -b "$root_part" ]]; then
        root_part="${loop_device}p1"
    fi
    
    if [[ -b "$root_part" ]]; then
        mount "$root_part" "$loop_mount" || {
            log_error "  Failed to mount $root_part"
            losetup -d "$loop_device"
            return 1
        }
        
        # Copy root filesystem
        log_info "  Copying root filesystem (this may take a while)..."
        rsync -aHAXx --info=progress2 "$loop_mount/" "$target_mount/" 2>&1 | tee -a "$LOG_FILE"
        
        # Unmount and cleanup
        umount "$loop_mount"
        log_success "  Filesystem copied successfully"
    else
        log_error "  Could not find root partition in image"
    fi
    
    # Cleanup
    losetup -d "$loop_device"
    [[ -f "$decompressed" ]] && rm -f "$decompressed"
    rmdir "$loop_mount" 2>/dev/null || true
    
    log_success "$os_name installation completed"
    return 0
}

# Install Kubuntu if image exists
KUBUNTU_IMG="$IMAGES_DIR/kubuntu-raspi.img.xz"
if [[ -f "$KUBUNTU_IMG" ]]; then
    install_os_image "$KUBUNTU_IMG" "$MOUNT_KUBUNTU" "kubuntu"
else
    log_warning "Kubuntu image not found: $KUBUNTU_IMG"
    log_warning "Creating placeholder in Kubuntu partition"
    echo "Kubuntu placeholder - image not installed" > "$MOUNT_KUBUNTU/README.txt"
    echo "Run acquire.sh to download the OS image, then re-run install.sh" >> "$MOUNT_KUBUNTU/README.txt"
fi

# Install Fedora if image exists
FEDORA_IMG="$IMAGES_DIR/fedora-raspi.img.xz"
if [[ -f "$FEDORA_IMG" ]]; then
    install_os_image "$FEDORA_IMG" "$MOUNT_FEDORA" "fedora"
else
    log_warning "Fedora image not found: $FEDORA_IMG"
    log_warning "Creating placeholder in Fedora partition"
    echo "Fedora placeholder - image not installed" > "$MOUNT_FEDORA/README.txt"
    echo "Run acquire.sh to download the OS image, then re-run install.sh" >> "$MOUNT_FEDORA/README.txt"
fi

log "Phase 4: Finalizing Boot Configuration"
log "-------------------------------------------------------------------"

# Copy kernels to boot partition if they exist in the OS installations
log_info "Extracting kernels to boot partition..."

if [[ -f "$MOUNT_KUBUNTU/boot/vmlinuz" ]]; then
    cp "$MOUNT_KUBUNTU/boot/vmlinuz" "$MOUNT_BOOT/kernels/kubuntu/" 2>&1 | tee -a "$LOG_FILE"
    cp "$MOUNT_KUBUNTU/boot/initrd.img" "$MOUNT_BOOT/kernels/kubuntu/" 2>&1 | tee -a "$LOG_FILE" || true
    log_success "  Kubuntu kernel copied"
else
    log_warning "  Kubuntu kernel not found (may need manual installation)"
fi

if [[ -f "$MOUNT_FEDORA/boot/vmlinuz" ]]; then
    cp "$MOUNT_FEDORA/boot/vmlinuz-"* "$MOUNT_BOOT/kernels/fedora/vmlinuz" 2>&1 | tee -a "$LOG_FILE" || true
    cp "$MOUNT_FEDORA/boot/initramfs-"* "$MOUNT_BOOT/kernels/fedora/initrd.img" 2>&1 | tee -a "$LOG_FILE" || true
    log_success "  Fedora kernel copied"
else
    log_warning "  Fedora kernel not found (may need manual installation)"
fi

# Create installation summary on data partition
log "Phase 5: Creating Installation Summary"
log "-------------------------------------------------------------------"

INSTALL_SUMMARY="$MOUNT_DATA/MULTIBOOT_SUMMARY.txt"
cat > "$INSTALL_SUMMARY" <<EOF
=================================================================
Raspberry Pi 5 Multiboot Installation Summary
=================================================================

Installation Date: $(date)
Target Device: $TARGET_DEVICE

Partition Layout:
-----------------
FIRMWARE_A: $FIRMWARE_PARTITION
  Mount: $MOUNT_FIRMWARE
  Type:  FAT32
  Size:  $(df -h "$MOUNT_FIRMWARE" | tail -1 | awk '{print $2}')
  Used:  $(df -h "$MOUNT_FIRMWARE" | tail -1 | awk '{print $3}')

BOOT_GRUB: $BOOT_PARTITION
  Mount: $MOUNT_BOOT
  Type:  ext4
  Size:  $(df -h "$MOUNT_BOOT" | tail -1 | awk '{print $2}')
  Used:  $(df -h "$MOUNT_BOOT" | tail -1 | awk '{print $3}')
  UUID:  $(blkid -s UUID -o value "$BOOT_PARTITION")

KUBUNTU: $KUBUNTU_PARTITION
  Mount: $MOUNT_KUBUNTU
  Type:  ext4
  Size:  $(df -h "$MOUNT_KUBUNTU" | tail -1 | awk '{print $2}')
  Used:  $(df -h "$MOUNT_KUBUNTU" | tail -1 | awk '{print $3}')
  UUID:  $KUBUNTU_UUID

FEDORA: $FEDORA_PARTITION
  Mount: $MOUNT_FEDORA
  Type:  ext4
  Size:  $(df -h "$MOUNT_FEDORA" | tail -1 | awk '{print $2}')
  Used:  $(df -h "$MOUNT_FEDORA" | tail -1 | awk '{print $3}')
  UUID:  $FEDORA_UUID

DATA: $DATA_PARTITION
  Mount: $MOUNT_DATA
  Type:  exFAT
  Size:  $(df -h "$MOUNT_DATA" | tail -1 | awk '{print $2}')
  Used:  $(df -h "$MOUNT_DATA" | tail -1 | awk '{print $3}')

SWAP: $SWAP_PARTITION
  Type:  swap
  Size:  $(swapon --show=SIZE --noheadings "$SWAP_PARTITION" 2>/dev/null || echo "N/A")

Boot Configuration:
-------------------
Firmware:    $MOUNT_FIRMWARE
GRUB Config: $MOUNT_BOOT/grub/grub.cfg
Kernels:     $MOUNT_BOOT/kernels/

Default Boot Order:
1. Kubuntu
2. Fedora

Log Files:
----------
Prepare:  $(ls -t $LOG_DIR/prepare_*.log 2>/dev/null | head -1)
Acquire:  $(ls -t $LOG_DIR/acquire_*.log 2>/dev/null | head -1)
Install:  $LOG_FILE

Next Steps:
-----------
1. Safely eject/unmount the NVMe device
2. Insert the NVMe into Raspberry Pi 5
3. Boot the device
4. Select your preferred OS from the GRUB menu

Troubleshooting:
----------------
- If the system doesn't boot, check firmware files in $MOUNT_FIRMWARE
- To update GRUB config, edit $MOUNT_BOOT/grub/grub.cfg
- Logs are available in: $LOG_DIR

=================================================================
EOF

log_success "Installation summary created: $INSTALL_SUMMARY"
cat "$INSTALL_SUMMARY" | tee -a "$LOG_FILE"

sync

log_success "==================================================================="
log_success "INSTALL phase completed successfully!"
log_success "==================================================================="
log_success "The multiboot NVMe device is ready!"
log_success ""
log_success "Summary file created at: $INSTALL_SUMMARY"
log_success "Log file: $LOG_FILE"
log_success ""
log_success "IMPORTANT: Keep the partitions mounted if you need to make"
log_success "additional changes. Otherwise, unmount with:"
log_success "  umount $MOUNT_FIRMWARE"
log_success "  umount $MOUNT_BOOT"
log_success "  umount $MOUNT_KUBUNTU"
log_success "  umount $MOUNT_FEDORA"
log_success "  umount $MOUNT_DATA"
log_success "  swapoff $SWAP_PARTITION"
log_success ""
log_success "Then safely remove the NVMe device and install in your Raspberry Pi 5"
log_success "==================================================================="

exit 0
